catalog/urls.py
from django.urls import path
from catalog.apps import CatalogConfig

from catalog.views import ProductListView, HomeProductListView, ProductDetailView, \
    ContactsCreateView, FeedBackMessageSent, AddProduct, ProductCreated, unpublish_product, delete_product, \
    ProductUpdateView, CategoryProduct

app_name = CatalogConfig.name

urlpatterns = [
    path('', HomeProductListView.as_view(), name='home'),
    path('product_list/', ProductListView.as_view(), name='product_list'),
    path('products/<int:pk>', ProductDetailView.as_view(), name='product_detail'),
    path('contacts/', ContactsCreateView.as_view(), name='contacts'),
    path('contacts/success/', FeedBackMessageSent.as_view(), name='feedback_success'),
    path('add_product/', AddProduct.as_view(), name='add_product'),
    path('product_created/', ProductCreated.as_view(), name='product_created'),
    path('products/<int:pk>/unpublish', unpublish_product, name='unpublish_product'),
    path('products/<int:pk>/delete', delete_product, name='delete_product'),
    path('products/<int:pk>/edit', ProductUpdateView.as_view(), name='edit_product'),
    path('products/category/<int:category_id>/', CategoryProduct.as_view(), name='category_products'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('catalog/', include('catalog.urls', namespace='catalog')),
    path('skyblog/', include('skyblog.urls', namespace='skyblog')),
    path('users/', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

skyblog/urls.py
from django.urls import path
from skyblog.apps import SkyblogConfig

from skyblog.views import HomePostListView, PostListView, CreatePostView, EditPostView, BlogPostDetailView, \
    OnModerationView, PostDeleteView

app_name = SkyblogConfig.name

urlpatterns = [
    # path('base', BaseView.as_view(), name='base'),
    path('', HomePostListView.as_view(), name='home'),
    path('posts/', PostListView.as_view(), name='post_list'),
    path('posts/<int:pk>/', BlogPostDetailView.as_view(), name='post_detail'),
    path('posts/new/', CreatePostView.as_view(), name='new_post'),
    path('posts/<int:pk>/edit/', EditPostView.as_view(), name='edit_post'),
    path('posts/<int:pk>/delete/', PostDeleteView.as_view(), name='delete_post'),
    path('on_moderation/', OnModerationView.as_view(), name='on_moderation'),

]

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from users.apps import UsersConfig
from users.views import UserCreateView, email_verification, UserProfileUpdateView

app_name = UsersConfig.name

urlpatterns = [
    path('login/', LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', LogoutView.as_view(next_page='/catalog/'), name='logout'),
    path('register', UserCreateView.as_view(), name='register'),
    path('email-confirm/<str:token>/', email_verification, name='email-confirm'),
    path('profile/edit/', UserProfileUpdateView.as_view(), name='profile_edit')
]

skyblog/models.py
# Create your models here.
from django.db import models
from django.utils import timezone


class BlogPost(models.Model):
    title = models.CharField(max_length=200, verbose_name="Title")
    content = models.TextField(verbose_name="Content")
    preview_image = models.ImageField(upload_to='blog_previews/', null=True, blank=True, verbose_name="Blog previews")
    created_at = models.DateTimeField(default=timezone.now, verbose_name="Created at")
    is_published = models.BooleanField(default=False, verbose_name="Publication flag")
    views_count = models.PositiveIntegerField(default=0, verbose_name="Views count")

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "Blog post"
        verbose_name_plural = "Blog posts"
        ordering = ['-created_at']

skyblog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, TemplateView, DetailView, CreateView, UpdateView, DeleteView

from skyblog.models import BlogPost


# Create your views here.
class BaseView(TemplateView):
    """ Base page """
    template_name = 'skyblog/base.html'


class HomePostListView(ListView):
    """ Home page with the five latest blog posts """
    model = BlogPost
    template_name = 'skyblog/home.html'
    context_object_name = 'posts'

    def get_queryset(self):
        return BlogPost.objects.filter(is_published=True)[:5]


class PostListView(ListView):
    """ List of all the posts """
    model = BlogPost
    template_name = 'skyblog/post_list.html'
    context_object_name = 'posts'
    paginate_by = 10

    def get_queryset(self):
        return BlogPost.objects.filter(is_published=True)


class CreatePostView(LoginRequiredMixin, CreateView):
    """ Page for creating a post """
    model = BlogPost
    fields = ['title', 'content', 'preview_image']
    template_name = 'skyblog/form_post.html'
    success_url = reverse_lazy('skyblog:on_moderation')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form_title'] = 'New Post'
        return context


class EditPostView(LoginRequiredMixin, UpdateView):
    """ Page og editing post """
    model = BlogPost
    fields = ['title', 'content', 'preview_image']
    template_name = 'skyblog/form_post.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form_title'] = 'Edit Post'
        return context

    def get_success_url(self):
        post = self.get_object()
        return reverse('skyblog:post_detail', kwargs={'pk': post.pk})


class OnModerationView(TemplateView):
    """ Success page for Create and Edit """
    template_name = 'skyblog/on_moderation.html'


class BlogPostDetailView(DetailView):
    """ Page for detailed viewing of the post """
    model = BlogPost
    template_name = 'skyblog/post_detail.html'
    context_object_name = 'post'

    def get_object(self, queryset=None):
        obj = super().get_object(queryset)
        obj.views_count += 1
        obj.save()

        return obj


class PostDeleteView(LoginRequiredMixin, DeleteView):
    """ Page for deleting post """
    model = BlogPost
    template_name = 'skyblog/post_confirm_delete.html'
    success_url = reverse_lazy('skyblog:post_list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['post_title'] = self.object.title
        return context

skyblog/templates/base.html
{% load static %}
<!doctype html>
<html lang="en" data-bs-theme="auto">
<head>
    <script src="{% static '/js/color-modes.js' %}"></script>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.122.0">
    <title>{% block title %}Default Title{% endblock %}</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.3/examples/album/">

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@docsearch/css@3">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/custom.css' %}" rel="stylesheet">

    <meta name="theme-color" content="#712cf9">
</head>
<body>

{% include 'includes/theme_switcher.html' %}

<header data-bs-theme="dark">
    <!--
    {% include 'includes/inc_menu.html'%}
    -->
</header>

<main>
    <!--
    {% block content%}
    {% endblock %}
    -->
</main>

<footer class="text-body-secondary py-5 mt-3">
    <div class="container">
        <p class="float-end mb-1">
            <a href="#">Back to top</a>
        </p>
        <p class="mb-1">Created with &copy; Bootstrap</p>
        <p class="mb-0">New to Bootstrap? <a href="/">Visit the homepage</a> or read our <a href="/docs/5.3/getting-started/introduction/">getting started guide</a>.</p>
    </div>
</footer>
<script src="{% static '/js/bootstrap.bundle.min.js' %}"></script>

</body>
</html>

skyblog/templates/home.html
{% extends 'base.html' %}
{% load my_tags %}
{% block title %}Post list{% endblock %}
{% block content %}
{% include 'includes/skyblog_info.html' %}
<div class="album py-5 bg-body-tertiary">
    <div class="container">
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
            <!--
            {% for post in posts %}
                {% include 'includes/product_card.html' %}
            {% endfor %}
            -->
        </div>
        <div class="row justify-content-center mt-4">
            <div class="col-auto">
                <a class="btn btn-outline-primary btn-lg btn-block" href="{% url 'catalog:product_list' %}" role="button">See all</a>
            </div>
    </div>
    </div>
</div>
{% endblock %}