catalog/urls.py
from django.urls import path
from catalog.apps import CatalogConfig

from catalog.views import ProductListView, HomeProductListView, ProductDetailView, \
    ContactsCreateView, FeedBackMessageSent, AddProduct, ProductCreated, unpublish_product, delete_product, \
    ProductUpdateView, CategoryProduct

app_name = CatalogConfig.name

urlpatterns = [
    path('', HomeProductListView.as_view(), name='home'),
    path('product_list/', ProductListView.as_view(), name='product_list'),
    path('products/<int:pk>', ProductDetailView.as_view(), name='product_detail'),
    path('contacts/', ContactsCreateView.as_view(), name='contacts'),
    path('contacts/success/', FeedBackMessageSent.as_view(), name='feedback_success'),
    path('add_product/', AddProduct.as_view(), name='add_product'),
    path('product_created/', ProductCreated.as_view(), name='product_created'),
    path('products/<int:pk>/unpublish', unpublish_product, name='unpublish_product'),
    path('products/<int:pk>/delete', delete_product, name='delete_product'),
    path('products/<int:pk>/edit', ProductUpdateView.as_view(), name='edit_product'),
    path('products/category/<int:category_id>/', CategoryProduct.as_view(), name='category_products'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('catalog/', include('catalog.urls', namespace='catalog')),
    path('skyblog/', include('skyblog.urls', namespace='skyblog')),
    path('users/', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from users.apps import UsersConfig
from users.views import UserCreateView, email_verification, UserProfileUpdateView

app_name = UsersConfig.name

urlpatterns = [
    path('login/', LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', LogoutView.as_view(next_page='/catalog/'), name='logout'),
    path('register', UserCreateView.as_view(), name='register'),
    path('email-confirm/<str:token>/', email_verification, name='email-confirm'),
    path('profile/edit/', UserProfileUpdateView.as_view(), name='profile_edit')
]

catalog/models.py
from django.core.validators import RegexValidator
from django.db import models
from django.db.models import TextField

from users.models import User


# Create your models here.
class Category(models.Model):
    """ Represents category """
    name = models.CharField(max_length=150, verbose_name='Category name')
    description = models.TextField(verbose_name='Description')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'category'
        verbose_name_plural = 'categories'
        ordering = ['name']


class Product(models.Model):
    """ Represents product """
    name = models.CharField(max_length=150, verbose_name='Product name')
    description = models.TextField(verbose_name='Description')
    pic = models.ImageField(upload_to='photos/', verbose_name='Photo', blank=True, null=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='products', blank=True, null=True)
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='price')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Time of creation')
    changed_at = models.DateTimeField(auto_now=True, verbose_name='Time of changing')
    owner = models.ForeignKey(User, on_delete=models.CASCADE, related_name='products', blank=True, null=True)

    STATUS_CHOICES = [
        ('DR', 'Draft'),
        ('PD', 'Pending'),
        ('PU', 'Published'),
        ('RJ', 'Rejected'),
    ]

    status = models.CharField(
        max_length=2,
        choices=STATUS_CHOICES,
        default='DR',
        verbose_name='Publication_Status'
    )

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'product'
        verbose_name_plural = 'products'
        ordering = ['-created_at']
        permissions = [
            ('can_unpublish_product', 'Can unpublish product'),
        ]


# Validator
phone_regex = RegexValidator(
    regex=r'^(\+?\d{1,3})?(\d{10})$',
    message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed."
)


class FeedBackMessage(models.Model):
    """ Represents Feedback Message """
    name = models.CharField(max_length=150, verbose_name='Name')
    phone = models.CharField(validators=[phone_regex], max_length=17, verbose_name='Phone number')
    message = TextField(verbose_name='Message', blank=False, null=False)
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Time of creation')

catalog/forms.py
from django import forms
from django.forms import BooleanField
from prompt_toolkit.validation import ValidationError

from .models import Product
from PIL import Image


forbidden_words = [
    'казино',
    'биржа',
    'обман',
    'криптовалюта',
    'дешево',
    'полиция',
    'крипта',
    'бесплатно',
    'радар'
]


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field, in self.fields.items():
            if isinstance(field, BooleanField):
                field.widget.attrs['class'] = 'form-check-input'
            else:
                field.widget.attrs['class'] = 'form-control'


class ProductForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Product
        fields = ['name', 'description', 'pic', 'category', 'price']

    def __init__(self, *args, **kwargs):
        super(ProductForm, self).__init__(*args, **kwargs)
        self.fields['name'].widget.attrs.update({
            'placeholder': 'Enter product name'
        })
        self.fields['description'].widget.attrs.update({
            'placeholder': 'Enter a description',
            'rows': 4
        })
        self.fields['pic'].widget.attrs.update({
            'accept': 'image/*',
            'id': 'custom_id_pic'
        })
        self.fields['price'].widget.attrs.update({
            'placeholder': 'Enter product price'
        })

    def clean_name(self):
        name = self.cleaned_data.get('name')
        for word in forbidden_words:
            if word in name.lower():
                raise forms.ValidationError(f'The word "{word}" is not allowed in the name')
        return name

    def clean_description(self):
        description = self.cleaned_data.get('description')
        for word in forbidden_words:
            if word in description.lower():
                raise forms.ValidationError(f'The word "{word}" is not allowed in the description')
        return description

    def clean_price(self):
        price = self.cleaned_data.get('price')
        if price <= 0:
            raise forms.ValidationError('Please enter a price greater than zero')
        return price

    def clean_pic(self):
        pic = self.cleaned_data.get('pic')
        if pic:
            if not pic.name.lower().endswith(('.jpg', '.jpeg', '.png')):
                raise forms.ValidationError('Unsupported file format')

            if pic.size > 5 * 1024 * 1024:
                raise forms.ValidationError('File size exceeds the limit of 5 MB.')

            try:
                with Image.open(pic) as img:
                    img.verify()
            except Exception:
                raise ValidationError('Invalid image file.')

        return pic

catalog/views.py
from django.contrib.auth.decorators import permission_required
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy
from django.views.decorators.cache import cache_page
from django.views.generic import ListView, DetailView, CreateView, TemplateView, UpdateView
from django.contrib import messages
from django.utils.decorators import method_decorator

from catalog.forms import ProductForm
from catalog.models import Product, FeedBackMessage
from catalog.services import ProductService


@permission_required('catalog.can_unpublish_product')
def unpublish_product(request, pk):
    product = get_object_or_404(Product, pk=pk)
    product.status = 'DR'
    product.save()
    messages.success(request, 'Product has unpublished successfully')
    return redirect('catalog:product_list')


@permission_required('catalog.delete_product')
def delete_product(request, pk):
    product = get_object_or_404(Product, pk=pk)
    product.delete()
    messages.success(request, 'Product has deleted successfully')
    return redirect('catalog:product_list')


class ProductListView(ListView):
    model = Product
    template_name = 'catalog/product_list.html'
    context_object_name = 'products'
    paginate_by = 10

    def get_queryset(self):
        return ProductService.get_products_from_cache().filter(status='PU')


class CategoryProduct(ListView):
    model = Product
    template_name = 'catalog/category_products.html'
    context_object_name = 'products'
    paginate_by = 10

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        category_id = self.kwargs['category_id']

        context['products'] = ProductService.filtered_by_category(category_id).filter(status='PU')
        context['category_name'] = ProductService.get_category_name(category_id)
        return context


@method_decorator(cache_page(60 * 15), name='dispatch')
class ProductDetailView(DetailView):
    """ Product detail page """
    model = Product
    template_name = 'catalog/product_detail.html'
    context_object_name = 'product'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['user'] = self.request.user
        return context


class HomeProductListView(ListView):
    model = Product
    template_name = 'catalog/home.html'
    context_object_name = 'products'

    def get_queryset(self):
        return Product.objects.filter(status='PU')[:5]


class ContactsCreateView(LoginRequiredMixin, CreateView):
    """ Page for Contacts with Feedback message feature """
    model = FeedBackMessage
    fields = ['name', 'phone', 'message']
    template_name = 'catalog/contacts.html'
    success_url = reverse_lazy('catalog:feedback_success')


class FeedBackMessageSent(TemplateView):
    template_name = 'catalog/feedback_success.html'


class AddProduct(LoginRequiredMixin, CreateView):
    model = Product
    form_class = ProductForm
    template_name = 'catalog/add_product.html'
    success_url = reverse_lazy('catalog:product_created')

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)


class ProductUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Product
    form_class = ProductForm
    template_name = 'catalog/edit_product.html'
    success_url = reverse_lazy('catalog:product_list')

    def test_func(self):
        obj = self.get_object()
        return obj.owner == self.request.user


class ProductCreated(TemplateView):
    template_name = 'catalog/product_created.html'

catalog/templates/catalog/includes/contacts_table.html
<div class="col-lg-9 col-md-6 col-sm-12">
    <div class="card mb-4 box-shadow">
        <div class="card-body">
            <table class="table table-striped">
                <tr>
                    <td class="w-25">State:</td>
                    <td>USA</td>
                </tr>
                <tr>
                    <td class="w-25">ID:</td>
                    <td>91-1144442</td>
                </tr>
                <tr>
                    <td class="w-25">Address:</td>
                    <td>Redmond,WA,98052-6399</td>
                </tr>
            </table>
        </div>
    </div>
</div>

catalog/templates/catalog/includes/inc_menu.html
<div class="collapse text-bg-dark" id="navbarHeader">
    <div class="container">
        <div class="row">
            <div class="col-sm-8 col-md-7 py-4">
                <h4>Skyshop</h4>
                <p class="text-body-secondary">This project is created for educational purposes. Demonstrates mastery of the Django framework, working with databases, and templating</p>
            </div>
            <div class="col-sm-4 offset-md-1 py-4">
                <h4>Menu</h4>
                <ul class="list-unstyled">
                    <li><a href="{% url 'catalog:home' %}" class="btn">Home</a></li>
                    <li><a href="{% url 'skyblog:home' %}" class="btn">Blog</a></li>
                    {% if user.is_authenticated %}
                    <li><a href="{% url 'users:profile_edit' %}" class="btn">Edit Profile</a></li>
                    <li>
                        <form method="post" action="{% url 'users:logout' %}">
                            {% csrf_token %}
                            <button type="submit" class="btn">Logout</button>
                        </form>
                    </li>
                    {% else %}
                    <li><a href="{% url 'users:login' %}" class="btn">Login</a></li>
                    <li><a href="{% url 'users:register' %}" class="btn">Sign up</a></li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </div>
</div>
<div class="navbar navbar-dark bg-dark shadow-sm">
    <div class="container">
        <a href="#" class="navbar-brand d-flex align-items-center">
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
    </div>
</div>

catalog/templates/catalog/includes/pagination.html
<!-- Pagination -->
<div class="row mt-4">
    <div class="col-12">
        <nav aria-label="Page navigation">
            <ul class="pagination justify-content-center">
                {% if page_obj.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page=1">&laquo; first</a>
                </li>
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.previous_page_number }}">previous</a>
                </li>
                {% endif %}

                <li class="page-item disabled">
                    <span class="page-link">
                        Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
                    </span>
                </li>

                {% if page_obj.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.next_page_number }}">next</a>
                </li>
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
                </li>
                {% endif %}
            </ul>
        </nav>
    </div>
</div>

catalog/templates/catalog/includes/product_card.html
{% load my_tags %}
<div class="col">
    <div class="card shadow-sm">
        {% if product.pic %}
        <img src="{{ product.pic|media_filter }}" class="card-img-top fixed-size-image">
        {% else %}
        <div class="placeholder-image">
            <span>{{ product.name }}</span>
        </div>
        {% endif %}
        <div class="card-body">
            <h5>{{ product.name }}</h5>
            <p class="card-title">{{ product.description|truncatechars:100 }}</p>
            <!-- Buttons and small-text -->
            <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                    <!-- My button-->
                    <a class="btn btn-primary" href="{% url 'catalog:product_detail' product.pk %}" role="button">More</a>
                </div>
                <small class="text-muted"> {{ product.created_at|date:"d M Y" }}</small>
            </div>
        </div>
    </div>
</div>

catalog/templates/catalog/includes/skyshop_info.html
<section class="py-5 text-center container">
    <div class="row py-lg-5">
        <div class="col-lg-6 col-md-8 mx-auto">
            <h1 class="fw-light">Skyshop</h1>
            <p class="lead text-body-secondary">This product collection, created for a Django project, includes a variety of categories, from electronics to clothing. Each product contains detailed information, allowing you to test and demonstrate the functionality of your web application.</p>
            <p>
                {% if user.is_authenticated %}
                <a href="{% url 'catalog:add_product' %}" class="btn btn-primary my-2">Add product</a>
                {% else %}
                <a href="{% url 'users:register' %}" class="btn btn-primary my-2">Sign in</a>
                <a href="{% url 'users:login' %}" class="btn btn-secondary my-2">Login</a>
                {% endif %}
                <a href="{% url 'catalog:contacts' %}" class="btn btn-secondary my-2">Contacts</a>
            </p>
        </div>
    </div>
</section>

catalog/templates/catalog/includes/theme_switcher.html
<div class="dropdown position-fixed bottom-0 end-0 mb-3 me-3 bd-mode-toggle">
    <button class="btn btn-bd-primary py-2 dropdown-toggle d-flex align-items-center"
            id="bd-theme"
            type="button"
            aria-expanded="false"
            data-bs-toggle="dropdown"
            aria-label="Toggle theme (auto)">
        <svg class="bi my-1 theme-icon-active" width="1em" height="1em"><use href="#circle-half"></use></svg>
        <span class="visually-hidden" id="bd-theme-text">Toggle theme</span>
    </button>
    <ul class="dropdown-menu dropdown-menu-end shadow" aria-labelledby="bd-theme-text">
        <li>
            <button type="button" class="dropdown-item d-flex align-items-center" data-bs-theme-value="light" aria-pressed="false">
                <svg class="bi me-2 opacity-50" width="1em" height="1em"><use href="#sun-fill"></use></svg>
                Light
                <svg class="bi ms-auto d-none" width="1em" height="1em"><use href="#check2"></use></svg>
            </button>
        </li>
        <li>
            <button type="button" class="dropdown-item d-flex align-items-center" data-bs-theme-value="dark" aria-pressed="false">
                <svg class="bi me-2 opacity-50" width="1em" height="1em"><use href="#moon-stars-fill"></use></svg>
                Dark
                <svg class="bi ms-auto d-none" width="1em" height="1em"><use href="#check2"></use></svg>
            </button>
        </li>
        <li>
            <button type="button" class="dropdown-item d-flex align-items-center active" data-bs-theme-value="auto" aria-pressed="true">
                <svg class="bi me-2 opacity-50" width="1em" height="1em"><use href="#circle-half"></use></svg>
                Auto
                <svg class="bi ms-auto d-none" width="1em" height="1em"><use href="#check2"></use></svg>
            </button>
        </li>
    </ul>
</div>