catalog/urls.py
from django.urls import path
from catalog.apps import CatalogConfig

from catalog.views import ProductListView, HomeProductListView, ProductDetailView, \
    ContactsCreateView, FeedBackMessageSent, AddProduct, ProductCreated, unpublish_product, delete_product, \
    ProductUpdateView, CategoryProduct

app_name = CatalogConfig.name

urlpatterns = [
    path('', HomeProductListView.as_view(), name='home'),
    path('product_list/', ProductListView.as_view(), name='product_list'),
    path('products/<int:pk>', ProductDetailView.as_view(), name='product_detail'),
    path('contacts/', ContactsCreateView.as_view(), name='contacts'),
    path('contacts/success/', FeedBackMessageSent.as_view(), name='feedback_success'),
    path('add_product/', AddProduct.as_view(), name='add_product'),
    path('product_created/', ProductCreated.as_view(), name='product_created'),
    path('products/<int:pk>/unpublish', unpublish_product, name='unpublish_product'),
    path('products/<int:pk>/delete', delete_product, name='delete_product'),
    path('products/<int:pk>/edit', ProductUpdateView.as_view(), name='edit_product'),
    path('products/category/<int:category_id>/', CategoryProduct.as_view(), name='category_products'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('catalog/', include('catalog.urls', namespace='catalog')),
    path('skyblog/', include('skyblog.urls', namespace='skyblog')),
    path('users/', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

skyblog/urls.py
from django.urls import path
from skyblog.apps import SkyblogConfig

from skyblog.views import HomePostListView, PostListView, CreatePostView, EditPostView, BlogPostDetailView, \
    OnModerationView, PostDeleteView

app_name = SkyblogConfig.name

urlpatterns = [
    # path('base', BaseView.as_view(), name='base'),
    path('', HomePostListView.as_view(), name='home'),
    path('posts/', PostListView.as_view(), name='post_list'),
    path('posts/<int:pk>/', BlogPostDetailView.as_view(), name='post_detail'),
    path('posts/new/', CreatePostView.as_view(), name='new_post'),
    path('posts/<int:pk>/edit/', EditPostView.as_view(), name='edit_post'),
    path('posts/<int:pk>/delete/', PostDeleteView.as_view(), name='delete_post'),
    path('on_moderation/', OnModerationView.as_view(), name='on_moderation'),

]

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from users.apps import UsersConfig
from users.views import UserCreateView, email_verification, UserProfileUpdateView

app_name = UsersConfig.name

urlpatterns = [
    path('login/', LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', LogoutView.as_view(next_page='/catalog/'), name='logout'),
    path('register', UserCreateView.as_view(), name='register'),
    path('email-confirm/<str:token>/', email_verification, name='email-confirm'),
    path('profile/edit/', UserProfileUpdateView.as_view(), name='profile_edit')
]

skyblog/models.py
# Create your models here.
from django.db import models
from django.utils import timezone


class BlogPost(models.Model):
    title = models.CharField(max_length=200, verbose_name="Title")
    content = models.TextField(verbose_name="Content")
    preview_image = models.ImageField(upload_to='blog_previews/', null=True, blank=True, verbose_name="Blog previews")
    created_at = models.DateTimeField(default=timezone.now, verbose_name="Created at")
    is_published = models.BooleanField(default=False, verbose_name="Publication flag")
    views_count = models.PositiveIntegerField(default=0, verbose_name="Views count")

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "Blog post"
        verbose_name_plural = "Blog posts"
        ordering = ['-created_at']

skyblog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, TemplateView, DetailView, CreateView, UpdateView, DeleteView

from skyblog.models import BlogPost


# Create your views here.
class BaseView(TemplateView):
    """ Base page """
    template_name = 'skyblog/base.html'


class HomePostListView(ListView):
    """ Home page with the five latest blog posts """
    model = BlogPost
    template_name = 'skyblog/home.html'
    context_object_name = 'posts'

    def get_queryset(self):
        return BlogPost.objects.filter(is_published=True)[:5]


class PostListView(ListView):
    """ List of all the posts """
    model = BlogPost
    template_name = 'skyblog/post_list.html'
    context_object_name = 'posts'
    paginate_by = 10

    def get_queryset(self):
        return BlogPost.objects.filter(is_published=True)


class CreatePostView(LoginRequiredMixin, CreateView):
    """ Page for creating a post """
    model = BlogPost
    fields = ['title', 'content', 'preview_image']
    template_name = 'skyblog/form_post.html'
    success_url = reverse_lazy('skyblog:on_moderation')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form_title'] = 'New Post'
        return context


class EditPostView(LoginRequiredMixin, UpdateView):
    """ Page og editing post """
    model = BlogPost
    fields = ['title', 'content', 'preview_image']
    template_name = 'skyblog/form_post.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form_title'] = 'Edit Post'
        return context

    def get_success_url(self):
        post = self.get_object()
        return reverse('skyblog:post_detail', kwargs={'pk': post.pk})


class OnModerationView(TemplateView):
    """ Success page for Create and Edit """
    template_name = 'skyblog/on_moderation.html'


class BlogPostDetailView(DetailView):
    """ Page for detailed viewing of the post """
    model = BlogPost
    template_name = 'skyblog/post_detail.html'
    context_object_name = 'post'

    def get_object(self, queryset=None):
        obj = super().get_object(queryset)
        obj.views_count += 1
        obj.save()

        return obj


class PostDeleteView(LoginRequiredMixin, DeleteView):
    """ Page for deleting post """
    model = BlogPost
    template_name = 'skyblog/post_confirm_delete.html'
    success_url = reverse_lazy('skyblog:post_list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['post_title'] = self.object.title
        return context

skyblog/templates/skyblog/includes/inc_menu.html
<div class="collapse text-bg-dark" id="navbarHeader">
    <div class="container">
      <div class="row">
        <div class="col-sm-8 col-md-7 py-4">
          <h4>Skyblog</h4>
          <p class="text-body-secondary">This project is created for educational purposes. Demonstrates mastery of the Django framework, working with databases, and templating</p>
        </div>
        <div class="col-sm-4 offset-md-1 py-4">
          <h4>Menu</h4>
          <ul class="list-unstyled">
            <li><a href="{% url 'skyblog:home' %}" class="btn">Home</a></li>
            <li><a href="{% url 'catalog:home' %}" class="btn">Skyshop</a></li>
            {% if user.is_authenticated %}
            <li><a href="{% url 'users:profile_edit' %}" class="btn">Edit Profile</a></li>
            <li>
                <form method="post" action="{% url 'users:logout' %}">
                    {% csrf_token %}
                    <button type="submit" class="btn">Logout</button>
                </form>
            </li>
            {% else %}
            <li><a href="{% url 'users:login' %}" class="btn">Login</a></li>
            <li><a href="{% url 'users:register' %}" class="btn">Sign up</a></li>
            {% endif %}
            <li><a href="#" class="btn">Contacts</a></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <div class="navbar navbar-dark bg-dark shadow-sm">
    <div class="container">
      <a href="#" class="navbar-brand d-flex align-items-center">
      </a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    </div>
  </div>

skyblog/templates/skyblog/includes/post_card.html
{% load my_tags %}
<div class="col">
    <div class="card shadow-sm">
        {% if post.preview_image %}
        <img src="{{ post.preview_image|media_filter }}" class="card-img-top fixed-size-image">
        {% else %}
        <div class="placeholder-image">
            <span>{{ post.title }}</span>
        </div>
        {% endif %}
        <div class="card-body">
            <h5>{{ post.title }}</h5>
            <p class="card-title">{{ post.content|truncatechars:100 }}</p>
            <!-- Buttons and small-text -->
            <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                    <!-- My button-->
                    <a class="btn btn-primary-outline" href="{% url 'skyblog:post_detail' post.pk %}" role="button">More</a>
                    <!--
                    <a class="btn btn-primary-outline" href="{% url 'skyblog:edit_post' post.pk %}" role="button">Edit</a>
                    -->
                    <!--
                    <a class="btn btn-primary-outline" href="{% url 'skyblog:delete_post' post.pk %}" role="button">Edit</a>
                    -->
                </div>
                <small class="text-muted">Views: {{ post.views_count }}</small>
            </div>
        </div>
    </div>
</div>

skyblog/templates/skyblog/includes/skyblog_info.html
<section class="py-5 text-center container">
    <div class="row py-lg-5">
        <div class="col-lg-6 col-md-8 mx-auto">
            <h1 class="fw-light">Skyblog</h1>
            <p class="lead text-body-secondary">This product collection, created for a Django project, includes a variety of categories, from electronics to clothing. Each product contains detailed information, allowing you to test and demonstrate the functionality of your web application.</p>
            <p>
                {% if user.is_authenticated %}
                <a href="{% url 'skyblog:new_post' %}" class="btn btn-primary my-2">New Post</a>
                {% else %}
                <a href="{% url 'users:register' %}" class="btn btn-primary my-2">Sign in</a>
                <a href="{% url 'users:login' %}" class="btn btn-primary my-2">Login</a>
                {% endif %}
                <a href="{% url 'catalog:contacts' %}" class="btn btn-secondary my-2">Contacts</a>
            </p>
        </div>
    </div>
</section>

skyblog/templates/skyblog/includes/theme_switcher.html
<div class="dropdown position-fixed bottom-0 end-0 mb-3 me-3 bd-mode-toggle">
    <button class="btn btn-bd-primary py-2 dropdown-toggle d-flex align-items-center"
            id="bd-theme"
            type="button"
            aria-expanded="false"
            data-bs-toggle="dropdown"
            aria-label="Toggle theme (auto)">
        <!--
        <svg class="bi my-1 theme-icon-active" width="1em" height="1em"><use href="#circle-half"></use></svg>
        -->
        <p>Theme</p>
        <span class="visually-hidden" id="bd-theme-text">Toggle theme</span>
    </button>
    <ul class="dropdown-menu dropdown-menu-end shadow" aria-labelledby="bd-theme-text">
        <li>
            <button type="button" class="dropdown-item d-flex align-items-center" data-bs-theme-value="light" aria-pressed="false">
                <svg class="bi me-2 opacity-50" width="1em" height="1em"><use href="#sun-fill"></use></svg>
                Light
                <svg class="bi ms-auto d-none" width="1em" height="1em"><use href="#check2"></use></svg>
            </button>
        </li>
        <li>
            <button type="button" class="dropdown-item d-flex align-items-center" data-bs-theme-value="dark" aria-pressed="false">
                <svg class="bi me-2 opacity-50" width="1em" height="1em"><use href="#moon-stars-fill"></use></svg>
                Dark
                <svg class="bi ms-auto d-none" width="1em" height="1em"><use href="#check2"></use></svg>
            </button>
        </li>
        <li>
            <button type="button" class="dropdown-item d-flex align-items-center active" data-bs-theme-value="auto" aria-pressed="true">
                <svg class="bi me-2 opacity-50" width="1em" height="1em"><use href="#circle-half"></use></svg>
                Auto
                <svg class="bi ms-auto d-none" width="1em" height="1em"><use href="#check2"></use></svg>
            </button>
        </li>
    </ul>
</div>