catalog/urls.py
from django.urls import path
from catalog.apps import CatalogConfig

from catalog.views import ProductListView, HomeProductListView, ProductDetailView, \
    ContactsCreateView, FeedBackMessageSent, AddProduct, ProductCreated, unpublish_product, delete_product, \
    ProductUpdateView, CategoryProduct

app_name = CatalogConfig.name

urlpatterns = [
    path('', HomeProductListView.as_view(), name='home'),
    path('product_list/', ProductListView.as_view(), name='product_list'),
    path('products/<int:pk>', ProductDetailView.as_view(), name='product_detail'),
    path('contacts/', ContactsCreateView.as_view(), name='contacts'),
    path('contacts/success/', FeedBackMessageSent.as_view(), name='feedback_success'),
    path('add_product/', AddProduct.as_view(), name='add_product'),
    path('product_created/', ProductCreated.as_view(), name='product_created'),
    path('products/<int:pk>/unpublish', unpublish_product, name='unpublish_product'),
    path('products/<int:pk>/delete', delete_product, name='delete_product'),
    path('products/<int:pk>/edit', ProductUpdateView.as_view(), name='edit_product'),
    path('products/category/<int:category_id>/', CategoryProduct.as_view(), name='category_products'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('catalog/', include('catalog.urls', namespace='catalog')),
    path('skyblog/', include('skyblog.urls', namespace='skyblog')),
    path('users/', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from users.apps import UsersConfig
from users.views import UserCreateView, email_verification, UserProfileUpdateView

app_name = UsersConfig.name

urlpatterns = [
    path('login/', LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', LogoutView.as_view(next_page='/catalog/'), name='logout'),
    path('register', UserCreateView.as_view(), name='register'),
    path('email-confirm/<str:token>/', email_verification, name='email-confirm'),
    path('profile/edit/', UserProfileUpdateView.as_view(), name='profile_edit')
]

catalog/models.py
from django.core.validators import RegexValidator
from django.db import models
from django.db.models import TextField

from users.models import User


# Create your models here.
class Category(models.Model):
    """ Represents category """
    name = models.CharField(max_length=150, verbose_name='Category name')
    description = models.TextField(verbose_name='Description')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'category'
        verbose_name_plural = 'categories'
        ordering = ['name']


class Product(models.Model):
    """ Represents product """
    name = models.CharField(max_length=150, verbose_name='Product name')
    description = models.TextField(verbose_name='Description')
    pic = models.ImageField(upload_to='photos/', verbose_name='Photo', blank=True, null=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='products', blank=True, null=True)
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='price')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Time of creation')
    changed_at = models.DateTimeField(auto_now=True, verbose_name='Time of changing')
    owner = models.ForeignKey(User, on_delete=models.CASCADE, related_name='products', blank=True, null=True)

    STATUS_CHOICES = [
        ('DR', 'Draft'),
        ('PD', 'Pending'),
        ('PU', 'Published'),
        ('RJ', 'Rejected'),
    ]

    status = models.CharField(
        max_length=2,
        choices=STATUS_CHOICES,
        default='DR',
        verbose_name='Publication_Status'
    )

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'product'
        verbose_name_plural = 'products'
        ordering = ['-created_at']
        permissions = [
            ('can_unpublish_product', 'Can unpublish product'),
        ]


# Validator
phone_regex = RegexValidator(
    regex=r'^(\+?\d{1,3})?(\d{10})$',
    message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed."
)


class FeedBackMessage(models.Model):
    """ Represents Feedback Message """
    name = models.CharField(max_length=150, verbose_name='Name')
    phone = models.CharField(validators=[phone_regex], max_length=17, verbose_name='Phone number')
    message = TextField(verbose_name='Message', blank=False, null=False)
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Time of creation')

catalog/forms.py
from django import forms
from django.forms import BooleanField
from prompt_toolkit.validation import ValidationError

from .models import Product
from PIL import Image


forbidden_words = [
    'казино',
    'биржа',
    'обман',
    'криптовалюта',
    'дешево',
    'полиция',
    'крипта',
    'бесплатно',
    'радар'
]


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field, in self.fields.items():
            if isinstance(field, BooleanField):
                field.widget.attrs['class'] = 'form-check-input'
            else:
                field.widget.attrs['class'] = 'form-control'


class ProductForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Product
        fields = ['name', 'description', 'pic', 'category', 'price']

    def __init__(self, *args, **kwargs):
        super(ProductForm, self).__init__(*args, **kwargs)
        self.fields['name'].widget.attrs.update({
            'placeholder': 'Enter product name'
        })
        self.fields['description'].widget.attrs.update({
            'placeholder': 'Enter a description',
            'rows': 4
        })
        self.fields['pic'].widget.attrs.update({
            'accept': 'image/*',
            'id': 'custom_id_pic'
        })
        self.fields['price'].widget.attrs.update({
            'placeholder': 'Enter product price'
        })

    def clean_name(self):
        name = self.cleaned_data.get('name')
        for word in forbidden_words:
            if word in name.lower():
                raise forms.ValidationError(f'The word "{word}" is not allowed in the name')
        return name

    def clean_description(self):
        description = self.cleaned_data.get('description')
        for word in forbidden_words:
            if word in description.lower():
                raise forms.ValidationError(f'The word "{word}" is not allowed in the description')
        return description

    def clean_price(self):
        price = self.cleaned_data.get('price')
        if price <= 0:
            raise forms.ValidationError('Please enter a price greater than zero')
        return price

    def clean_pic(self):
        pic = self.cleaned_data.get('pic')
        if pic:
            if not pic.name.lower().endswith(('.jpg', '.jpeg', '.png')):
                raise forms.ValidationError('Unsupported file format')

            if pic.size > 5 * 1024 * 1024:
                raise forms.ValidationError('File size exceeds the limit of 5 MB.')

            try:
                with Image.open(pic) as img:
                    img.verify()
            except Exception:
                raise ValidationError('Invalid image file.')

        return pic

catalog/views.py
from django.contrib.auth.decorators import permission_required
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy
from django.views.decorators.cache import cache_page
from django.views.generic import ListView, DetailView, CreateView, TemplateView, UpdateView
from django.contrib import messages
from django.utils.decorators import method_decorator

from catalog.forms import ProductForm
from catalog.models import Product, FeedBackMessage
from catalog.services import ProductService


@permission_required('catalog.can_unpublish_product')
def unpublish_product(request, pk):
    product = get_object_or_404(Product, pk=pk)
    product.status = 'DR'
    product.save()
    messages.success(request, 'Product has unpublished successfully')
    return redirect('catalog:product_list')


@permission_required('catalog.delete_product')
def delete_product(request, pk):
    product = get_object_or_404(Product, pk=pk)
    product.delete()
    messages.success(request, 'Product has deleted successfully')
    return redirect('catalog:product_list')


class ProductListView(ListView):
    model = Product
    template_name = 'catalog/product_list.html'
    context_object_name = 'products'
    paginate_by = 10

    def get_queryset(self):
        return ProductService.get_products_from_cache().filter(status='PU')


class CategoryProduct(ListView):
    model = Product
    template_name = 'catalog/category_products.html'
    context_object_name = 'products'
    paginate_by = 10

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        category_id = self.kwargs['category_id']

        context['products'] = ProductService.filtered_by_category(category_id).filter(status='PU')
        context['category_name'] = ProductService.get_category_name(category_id)
        return context


@method_decorator(cache_page(60 * 15), name='dispatch')
class ProductDetailView(DetailView):
    """ Product detail page """
    model = Product
    template_name = 'catalog/product_detail.html'
    context_object_name = 'product'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['user'] = self.request.user
        return context


class HomeProductListView(ListView):
    model = Product
    template_name = 'catalog/home.html'
    context_object_name = 'products'

    def get_queryset(self):
        return Product.objects.filter(status='PU')[:5]


class ContactsCreateView(LoginRequiredMixin, CreateView):
    """ Page for Contacts with Feedback message feature """
    model = FeedBackMessage
    fields = ['name', 'phone', 'message']
    template_name = 'catalog/contacts.html'
    success_url = reverse_lazy('catalog:feedback_success')


class FeedBackMessageSent(TemplateView):
    template_name = 'catalog/feedback_success.html'


class AddProduct(LoginRequiredMixin, CreateView):
    model = Product
    form_class = ProductForm
    template_name = 'catalog/add_product.html'
    success_url = reverse_lazy('catalog:product_created')

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)


class ProductUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Product
    form_class = ProductForm
    template_name = 'catalog/edit_product.html'
    success_url = reverse_lazy('catalog:product_list')

    def test_func(self):
        obj = self.get_object()
        return obj.owner == self.request.user


class ProductCreated(TemplateView):
    template_name = 'catalog/product_created.html'

catalog/templates/catalog/add_product.html
{% extends 'catalog/base.html' %}
{% block title %}Add New Product{% endblock %}
{% block content %}
<div class="container">
    <h1 class="mt-5">Add New Product</h1>
    <form method="post" enctype="multipart/form-data" class="needs-validation" novalidate>
        {% csrf_token %}
        {{ form.non_field_errors }}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary mt-3">Add Product</button>
    </form>
</div>
{% endblock %}

catalog/templates/catalog/base.html
{% load static %}
<!doctype html>
<html lang="en" data-bs-theme="auto">
<head>
    <script src="{% static '/js/color-modes.js' %}"></script>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.122.0">
    <title>{% block title %}Default Title{% endblock %}</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.3/examples/album/">

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@docsearch/css@3">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/custom.css' %}" rel="stylesheet">

    <meta name="theme-color" content="#712cf9">
</head>
<body>

{% include 'catalog/includes/theme_switcher.html' %}

<header data-bs-theme="dark">
    {% include 'catalog/includes/inc_menu.html'%}
</header>

<main>
    {% block content%}
    {% endblock %}
</main>

<footer class="text-body-secondary py-5 mt-3">
    <div class="container">
        <p class="float-end mb-1">
            <a href="#">Back to top</a>
        </p>
        <p class="mb-1">Created with &copy; Bootstrap</p>
        <p class="mb-0">New to Bootstrap? <a href="/">Visit the homepage</a> or read our <a href="/docs/5.3/getting-started/introduction/">getting started guide</a>.</p>
    </div>
</footer>
<script src="{% static '/js/bootstrap.bundle.min.js' %}"></script>

</body>
</html>

catalog/templates/catalog/category_products.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block title %}Product in {{ category_name }}{% endblock %}
{% block content %}
<div class="album py-5 bg-body-tertiary">
    <h2 class="text-center mt-5 mb-5">Product in {{ category_name }}</h2>
    <div class="container">
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
            {% for product in products %}
                {% include 'catalog/includes/product_card.html' %}
            {% endfor %}
        </div>
        {% include 'catalog/includes/pagination.html' %}
    </div>
</div>
{% endblock %}

catalog/templates/catalog/contacts.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block title %}Contacts{% endblock %}
{% block content %}
<div class="container">
    <div class="row text-start">
        {% include 'catalog/includes/contacts_table.html'%}
        <div class="col-lg-3 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Feedback</h4>
                </div>
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="{{ form.name.id_for_label }}" class="form-label">Name:</label>
                            <input type="text" name="{{ form.name.name }}" id="{{ form.name.id_for_label }}" class="form-control {% if form.name.errors %}is-invalid{% endif %}" placeholder="Enter your name">
                            <div class="invalid-feedback">
                                {{ form.name.errors }}
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="{{ form.phone.id_for_label }}" class="form-label">Phone:</label>
                            <input type="text" name="{{ form.phone.name }}" id="{{ form.phone.id_for_label }}" class="form-control {% if form.phone.errors %}is-invalid{% endif %}" placeholder="Enter your phone number">
                            <div class="invalid-feedback">
                                {{ form.phone.errors }}
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="{{ form.message.id_for_label }}" class="form-label">Message:</label>
                            <textarea name="{{ form.message.name }}" id="{{ form.message.id_for_label }}" class="form-control {% if form.message.errors %}is-invalid{% endif %}" rows="5" placeholder="Enter your message"></textarea>
                            <div class="invalid-feedback">
                                {{ form.message.errors }}
                            </div>
                        </div>
                        <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Send</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/edit_product.html
{% extends 'catalog/base.html' %}
{% block title %}Edit Product{% endblock %}
{% block content %}
<div class="container">
    <h1 class="mt-5">Edit Product</h1>
    <form method="post" enctype="multipart/form-data" class="needs-validation" novalidate>
        {% csrf_token %}
        {{ form.non_field_errors }}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary mt-3">Save</button>
    </form>
</div>
{% endblock %}

catalog/templates/catalog/feedback_success.html
{% extends 'catalog/base.html' %}
{% block title %}Your message sent{% endblock %}
{% block content %}
<div class="container d-flex flex-column justify-content-center align-items-center">
  <div class="row">
    <h3>Your message sent</h3>
    <div class="col mt-4">
      <a class="btn btn-outline-primary btn-lg btn-block" href="{% url 'catalog:home' %}" role="button">
        Back to Home
      </a>
      <a class="btn btn-outline-primary btn-lg btn-block" href="{% url 'catalog:contacts' %}" role="button">
        Back to Contacts
      </a>
    </div>
  </div>
</div>
{% endblock %}

catalog/templates/catalog/home.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block title %}Product list{% endblock %}
{% block content %}
{% include 'catalog/includes/skyshop_info.html' %}
<div class="album py-5 bg-body-tertiary">
    <div class="container">
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">

            {% for product in products %}
                {% include 'catalog/includes/product_card.html' %}
            {% endfor %}
        </div>
        <div class="row justify-content-center mt-4">
            <div class="col-auto">
                <a class="btn btn-outline-primary btn-lg btn-block" href="{% url 'catalog:product_list' %}" role="button">See all</a>
            </div>
    </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/product_created.html
{% extends 'catalog/base.html' %}
{% block title %}Your message sent{% endblock %}
{% block content %}
<div class="container d-flex flex-column justify-content-center align-items-center" style="min-height: 70vh;">
    <h3>Your product added to the Catalog</h3>
    <div class="col mt-4">
        <a class="btn btn-outline-primary btn-lg btn-block" href="{% url 'catalog:home' %}" role="button">
            Back to Home
        </a>
        <a class="btn btn-outline-primary btn-lg btn-block" href="{% url 'catalog:add_product' %}" role="button">
            Add another one
        </a>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/product_detail.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block title %}Product Detail{% endblock %}
{% block content %}
<div class="container">
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
        <div class="col">
            <div class="card mb-3">
                {% if product.pic %}
                <img src="{{ product.pic|media_filter }}" class="card-img-top fit-cover-center" alt="Product Image">
                {% else %}
                <div class="placeholder-image">
                    <span>{{ product.name }}</span>
                </div>
                {% endif %}
                <div class="card-body">
                    <h5 class="card-title">{{ product.name }}</h5>
                    <p class="card-text">{{ product.description }}</p>
                </div>
                <ul class="list-group list-group-flush">
                    <li class="list-group-item">
                        Price: {{ product.price }}
                    </li>
                    <li class="list-group-item">
                        Category: {{ product.category }}
                    </li>
                    <li class="list-group-item">
                        Created at {{ product.created_at|date:"d M Y" }}
                    </li>
                    <li class="list-group-item">
                        Changed at: {{ product.changed_at|date:"d M Y" }}
                    </li>
                </ul>
            </div>
            <a class="btn btn-outline-primary btn-lg btn-block" href="{% url 'catalog:product_list' %}" role="button">Back</a>
            {% if perms.catalog.can_unpublish_product and product.status == 'PU' %}
                <a class="btn btn-outline-secondary btn-lg btn-block" href="{% url 'catalog:unpublish_product' product.pk %}">
                    Unpublish
                </a>
            {% endif %}
            {% if product.owner == user %}
                <a class="btn btn-outline-secondary btn-lg btn-block" href="{% url 'catalog:edit_product' product.pk%}">
                    Edit
                </a>
            {% endif %}
            {% if perms.catalog.delete_product %}
                <a class="btn btn-outline-danger btn-lg btn-block" href="{% url 'catalog:delete_product' product.pk %}">
                    Delete
                </a>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/product_list.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block title %}Product list{% endblock %}
{% block content %}
<div class="album py-5 bg-body-tertiary">
    <div class="container">
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
            {% for product in products %}
                {% include 'catalog/includes/product_card.html' %}
            {% endfor %}
        </div>
        {% include 'catalog/includes/pagination.html' %}
    </div>
</div>
{% endblock %}